version: '3.8'

services:
  anki:
    image: ghcr.io/yukaii/gakuon-headless-anki:latest
    volumes:
      - anki_data:/data
      - anki_export:/export
    #   Uncomment for first-time GUI setup
    #   - /tmp/container-xauth:/home/anki/.Xauthority:rw
    # environment:
    # - DISPLAY=${DISPLAY}
    # - QT_QPA_PLATFORM=xcb
    # - XAUTHORITY=/home/anki/.Xauthority
    # network_mode: host
    ports:
      - "8765:8765"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  gakuon:
    image: ghcr.io/yukaii/gakuon:latest
    ports:
      - "4989:4989"
    volumes:
      - gakuon_config:/root/.gakuon
    environment:
      - GAKUON_ANKI_HOST=http://anki:8765
    depends_on:
      anki:
        condition: service_healthy
    command: ["serve", "--serve-client", "--port", "4989"]

volumes:
  gakuon_config:
  anki_data:
  anki_export:
