version: '3.8'

services:
  anki:
    image: ghcr.io/yukaii/gakuon-headless-anki:latest
    volumes:
    # bring your own data
      - ./data:/data
      - ./export:/export
    ports:
      - "8765:8765"
    # environment:
    #   - DISPLAY=host.docker.internal:0
    #   - QT_QPA_PLATFORM=xcb⏎
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  gakuon:
    image: ghcr.io/yukaii/gakuon:latest
    ports:
      - "4989:4989"
    volumes:
      - gakuon_config:/root/.gakuon
    environment:
      - GAKUON_ANKI_HOST=http://anki:8765
    depends_on:
      anki:
        condition: service_healthy
    command: ["serve", "--serve-client", "--port", "4989"]

volumes:
  gakuon_config:
